### ISSUE TITLE
🚀 [Feature] : Integrate App Update plugin

### ISSUE THREAD

**Issue by behics** [languageXchange/languageXchange#449]
Edit: Check the plugin out that one for updates. 
- https://github.com/Cap-go
- https://github.com/Cap-go/capacitor-updater

> This repository has been archived by the owner on Apr 1, 2023. It is now read-only. 
https://github.com/capawesome-team/capacitor-app-update

![update_flow](https://github.com/languageXchange/languageXchange/assets/3280475/bf31c2a9-f758-48d0-9b26-34db2c290cd0)

**Comment by pizofreude** [comment]
I second this motion as many apps are using this feature nowadays, atleast the ones I use.

**Comment by behics** [comment]
> I second this motion as many apps are using this feature nowadays, atleast the ones I use. 

Yea, unfortunately we are still using traditional approach, i could guess but didnt know which library can i use for that.
We use only `javascript` after builds so we can integrate it as well.

### Google Play
Google play

Third paragraph of [Device and Network Abuse](https://support.google.com/googleplay/android-developer/answer/9888379?hl=en) topic describe that updating source code by any method other than Google Play's update mechanism is restricted. But this restriction does not apply to updating javascript bundles.

> This restriction does not apply to code that runs in a virtual machine and has limited access to Android APIs (such as JavaScript in a webview or browser).

That fully allow Capacitor-updater as it updates just JS bundles and can't update native code part.

### App Store

Paragraph 3.3.2, since back in 2015's [Apple Developer Program License Agreement](https://developer.apple.com/programs/ios/information/) fully allowed performing over-the-air updates of JavaScript and assets - and in its latest version (20170605) [downloadable here](https://developer.apple.com/terms/) this ruling is even 

> Interpreted code may be downloaded to an Application but only so long as such code: (a) does not change the primary purpose of the Application by providing features or functionality that are inconsistent with the intended and advertised purpose of the Application as submitted to the App Store, (b) does not create a store or storefront for other code or applications, and (c) does not bypass signing, sandbox, or other security features of the OS.

**Comment by behics** [comment]
Insprational: https://www.youtube.com/watch?v=NJwBNWwNlTk
