### ISSUE TITLE
🚀 [Feature] :  Update beta version in readme

### ISSUE THREAD

**Issue by pizofreude** [languageXchange/languageXchange#503]
**Is your feature request related to a problem? Please describe.**
I would prefer to see exact version from the get-go in the readme for efficiency without having to go deeper just to ensure the actual version.

**Describe the solution you'd like**
Currently the default is a general version with this format: Beta phase v0.X.x. I volunteer to keep this up-to-date accordingly for the readme i.e. Beta phase v0.5.17.

**Describe alternatives you've considered**
There are automation tools for this purpose. One such tool is Renovatebot, which is a universal dependency update tool that can be configured to update README file as part of its automation process. Another option is readme-ai, an automated README file generator that can create and update README files using data extraction and generative AI. Though I haven't had the chance to use them yet. Will research more on them in the future.

**Additional context**
This serves for better clarity in documentation.

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by pizofreude** [comment]
@behics can you add the label "documentation" for this and assign me for it? I'll do it asap. Cheers 🤝

**Comment by behics** [comment]
- [ ] Mention it in Table Of Contents if you create new Title (header) inside of README

**Comment by pizofreude** [comment]
@behics can we close this now as the PR is already completed? Thanks 👍🏻

**Comment by behics** [comment]
> @behics can we close this now as the PR is already completed? Thanks 👍🏻

Thank you ! :)
